#!/usr/bin/env python3
"""
Simple script to open and view the latest plots
"""

import os
import subprocess
import sys

def open_plots():
    """Open the latest plots using the default image viewer"""
    
    plot_dir = "performance_plots"
    if not os.path.exists(plot_dir):
        print(f"❌ Directory {plot_dir} not found!")
        return
    
    # List of key plots to show (latest versions)
    key_plots = [
        "training_history_Shellcode_latest.png",
        "confusion_matrices__base_model_latest.png", 
        "client_performance_latest.png",
        "blockchain_metrics_latest.png",
        "gas_usage_analysis_latest.png",
        "performance_comparison_annotated_Shellcode_latest.png",
        "token_distribution_Shellcode_latest.png"
    ]
    
    # IEEE Statistical plots (automatically generated by main.py)
    ieee_plots = [
        "ieee_statistical_plots/ieee_evaluation_methodology_comparison.png",
        "ieee_statistical_plots/ieee_kfold_cross_validation.png",
        "ieee_statistical_plots/ieee_meta_tasks_evaluation.png",
        "ieee_statistical_plots/ieee_statistical_comparison.png",  # Unified plot with all metrics
        "ieee_statistical_plots/ieee_effect_size_analysis.png"
    ]
    
    all_plots = key_plots + ieee_plots
    
    print("📊 Opening key visualization plots...")
    
    for plot_name in all_plots:
        plot_path = os.path.join(plot_dir, plot_name)
        if os.path.exists(plot_path):
            print(f"  📈 Opening: {plot_name}")
            try:
                # Open with default image viewer
                if sys.platform.startswith('win'):
                    os.startfile(plot_path)
                elif sys.platform.startswith('darwin'):  # macOS
                    subprocess.run(['open', plot_path])
                else:  # Linux
                    subprocess.run(['xdg-open', plot_path])
            except Exception as e:
                print(f"    ❌ Error opening {plot_name}: {e}")
        else:
            print(f"  ⚠️  Not found: {plot_name}")
    
    print("✅ All plots should now be open in your default image viewer!")

if __name__ == "__main__":
    open_plots()
